server: ":57314"
coordinator:
  addr: 'coordinator:6379'
  db: 0
  pool: 100
  read: 10s
#  blockingpoptime: 5s
gatekeeper:
  addr: 'gatekeeper:6379'
  db: 0
  pool: 100
  read: 10s
  ttl: 1h
response:
  log: "/var/log/strelka/strelka.log"
