name: "build main daily"
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  strelka:
    name: "build mail daily"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
