name: "build main"
on:
  push
jobs:
  strelka:
    name: "build main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
