name: "Build Strelka Master"
on:
  push
jobs:
  strelka:
    name: "Build Strelka Master"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
