name: "Fileshot"
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  strelka:
    name: "build strelka fileshot daily"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka Fileshot
        run: docker build -f build/go/fileshot/Dockerfile .
