name: "Pull Request Build"
on:
  pull_request:
    branches: [ master ]
jobs:
  strelka:
    name: "Strelka Pull Request Build"
    env:
        DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
