name: "Oneshot"
on:
  schedule:
    - cron: '0 4 * * *'
jobs:
  strelka:
    name: "build strelka onshot daily"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka Oneshot
        run: docker build -f build/go/oneshot/Dockerfile .
