name: "Push Build"
on:
  push
jobs:
  strelka:
    name: "Strelka Push Build"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run:  |
          export DOCKER_BUILDKIT=1
          docker-compose -f build/docker-compose.yaml build
