name: "Push Build"
on:
  push
jobs:
  strelka:
    name: "Build Strelka (Main Push)"
    env:
        DOCKER_BUILDKIT: 1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
