name: pr-actions
on: [pull_request]

jobs:
  backend-strelka-test:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:

          python-version: '3.10'

          architecture: 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install --no-install-recommends -qq \
          automake \
          build-essential \
          curl \
          gcc \
          git \
          libglu1-mesa \
          libtool \
          make \
          swig \
          python3-dev \
          python3-pip \
          python3-wheel \
          pkg-config \
          7zip=21.07+dfsg-4 \
          antiword \
          libarchive-dev \
          libfuzzy-dev \
          libmagic-dev \
          libssl-dev \
          libzbar0 \
          libgl1 \
          python3-setuptools \
          redis-server \
          tesseract-ocr \
          unrar \
          upx \
          jq \
          exiftool && \
          python -m pip install --upgrade pip
          pip install validators setuptools --upgrade
          pip install --no-cache-dir -r src/python/requirements.txt
      - name: Test with pytest
        run: |
          pytest
      
