name: pr-actions
on: [pull_request]

jobs:
  backend-strelka-test:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:

          python-version: '3.10'

          architecture: 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install --no-install-recommends -qq \
          automake \
          build-essential \
          curl \
          gcc \
          git \
          libglu1-mesa \
          libtool \
          make \
          swig \
          python3-dev \
          python3-pip \
          python3-wheel \
          pkg-config \
          7zip=21.07+dfsg-4 \
          antiword \
          libarchive-dev \
          libfuzzy-dev \
          libmagic-dev \
          libssl-dev \
          libzbar0 \
          libgl1 \
          python3-setuptools \
          redis-server \
          tesseract-ocr \
          unrar \
          upx \
          jq && \
          python -m pip install --upgrade pip
          pip install validators setuptools --upgrade
          pip install --no-cache-dir -r src/python/requirements.txt
      - name: Install exiftool
        run: |
          cd /tmp/ && \
          curl -OL https://github.com/exiftool/exiftool/archive/refs/tags/12.52.tar.gz && \
          tar -zxvf 12.52.tar.gz && \
          cd exiftool-12.52/ && \
          perl Makefile.PL && \
          make && \
          sudo make install
      - name: Install JTR dependencies
        run: |
          sudo apt-get install --no-install-recommends -qq \
          ca-certificates \
          libssl-dev \
          zlib1g-dev \
          yasm \
          libgmp-dev \
          libpcap-dev \
          libbz2-dev \
          libgomp1
      - name: Install JTR
        run: |
          sudo mkdir /jtr \
          && cd /jtr \
          && sudo chmod -R 777 /jtr \
          && git init && git remote add origin https://github.com/openwall/john.git && git fetch --depth 1 origin b5c10480f56ff1b5d76c6cbdaf9c817582ee2228 && git reset --hard FETCH_HEAD \
          && rm -rf /jtr/.git \
          && cd /jtr/src \
          && ./configure \
          && make -s clean \
          && make -sj4 \
          && sudo make install \
          && cp -Tr /jtr/run/ /jtr && rm -rf /jtr/run
      - name: Inject password for JTR test
        run: |
          sudo mkdir /etc/strelka/ \
          && sudo echo password > /etc/strelka/passwords.dat
      - name: Check passwords for JTR test
        run: |
          sudo cat /etc/strelka/passwords.dat
      - name: Test with pytest
        run: |
          pytest
