name: Publish Latest Images to Docker Hub

on:
  push:
    branches: [publish-images]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Action Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Images
        run: |
          export COMMIT_HASH=$(git rev-parse --short HEAD)
          export TAG_NAME=$(git describe --tags --abbrev=0)
          export IMAGE_NAME=target/strelka-fileshot

          docker build -f build/go/fileshot/Dockerfile -t $IMAGE_NAME:$COMMIT_HASH -t $IMAGE_NAME:$TAG_NAME .

      - name: Push Images to Docker Hub
        run: |
          export COMMIT_HASH=$(git rev-parse --short HEAD)
          export TAG_NAME=$(git describe --tags --abbrev=0)
          export IMAGE_NAME=target/strelka-fileshot
          
          docker push $IMAGE_NAME:$COMMIT_HASH
          docker push $IMAGE_NAME:$TAG_NAME
