---
name: Style Automation
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/python/requirements.txt

      - name: Code quality checks
        run: |
          - python -m venv /tmp/.venv
          - . /tmp/.venv/bin/activate
          - pip
          - python -m black --check --diff .
          - python -m mypy .
          - python -m flake8 .
          - python -m isort --check-only .
