client: 'go-fileshot-default'
conn:
  server: 'localhost:57314'
  #cert: './cert/devtest.crt'
  timeout:
    dial: 5s
    file: 5m
throughput:
  concurrency: 8
  chunk: 98304
  delay: 1s
files:
  patterns:
    - '/glob/to/your/files/*'
  minsize: 0
  maxsize: 9999999999
  limitpattern: 999
  limittotal: 99999
  modified: 99999
  mimetypes:
    - 'application/mimetype'
  delete: false
  gatekeeper: false
response:
  log: 'strelka.log'
